# Copyright (C) 2017 Bogdan Bogush <bogdan.s.bogush@gmail.com>
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3.

PROG_DIR=programmer

all:
	$(MAKE) -C $(PROG_DIR)

clean:
	$(MAKE) -C $(PROG_DIR) clean

distclean:
	$(MAKE) -C $(PROG_DIR) distclean

program:
	$(MAKE) -C $(PROG_DIR) program
